name: Publish Latest Docker Images to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push multi-platform docker images to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          # cache: "pnpm"

      # - uses: pnpm/action-setup@v4
      #   name: Install pnpm
      #   with:
      #     run_install: false

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy Dockerfile
        run: cp node_modules/@browserless.io/browserless/docker/sdk/Dockerfile ./build/Dockerfile

      - name: Add browser install command to Dockerfile
        run: sed -i '/RUN npm install/a RUN npm run install:browsers' ./build/Dockerfile

      - name: Add static files to Dockerfile
        run: sed -i '/COPY src src/a COPY static static' ./build/Dockerfile

      - name: Add start script to Dockerfile
        run: sed -i '/COPY static static/a COPY start.sh .' ./build/Dockerfile

      - name: Make start script executable in Dockerfile
        run: sed -i '/COPY start.sh .*/a RUN chmod +x ./start.sh' ./build/Dockerfile

      - name: Change CMD in Dockerfile
        run: sed -i 's|CMD \["npm", "start"\]|CMD \["./start.sh"\]|' ./build/Dockerfile

      - name: Publish the latest Multi image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=latest
            FROM=ghcr.io/browserless/multi:latest
          builder: ${{ steps.buildx.outputs.name }}
          file: ./build/Dockerfile
          tags: |
            ghcr.io/oudyworks/browserless:latest
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64
